on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install shellcheck
        run: |
          curl -OL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
          tar -xvf shellcheck-stable.linux.x86_64.tar.xz
          echo "$(pwd)/shellcheck-stable" >> "$GITHUB_PATH"

      - name: lint bash script
        run: shellcheck **/*.sh

      - name: lint zsh script
        run: shellcheck **/*.zsh
