on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: zsh script
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          additional_files: .zshrc
        env:
          SHELLCHECK_OPTS: -e SC1091